-- CreateTable
CREATE TABLE `products` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `slug` VARCHAR(191) NOT NULL,
    `date_added` VARCHAR(191) NULL,
    `product_family` VARCHAR(191) NULL,
    `use` VARCHAR(191) NULL,
    `model` VARCHAR(191) NULL,
    `product_name` VARCHAR(191) NULL,
    `sku_number` VARCHAR(191) NULL,
    `size` VARCHAR(191) NULL,
    `picture` JSON NULL,
    `product_summary` TEXT NULL,
    `long_description` TEXT NULL,
    `supplier_url` TEXT NULL,
    `pixel_pitch` VARCHAR(191) NULL,
    `screen_type` VARCHAR(191) NULL,
    `supplier` VARCHAR(191) NULL,
    `oc_brand` VARCHAR(191) NULL,
    `mount` VARCHAR(191) NULL,
    `sides` VARCHAR(191) NULL,
    `indoor_outdoor` VARCHAR(191) NULL,
    `outdoor_rating` VARCHAR(191) NULL,
    `operating_system` VARCHAR(191) NULL,
    `processor` VARCHAR(191) NULL,
    `ram` VARCHAR(191) NULL,
    `rom` VARCHAR(191) NULL,
    `brightness` VARCHAR(191) NULL,
    `cabinet_size` VARCHAR(191) NULL,
    `cabinet_qty` VARCHAR(191) NULL,
    `cabinet_weight` VARCHAR(191) NULL,
    `screen_dimension` VARCHAR(191) NULL,
    `outer_size` VARCHAR(191) NULL,
    `lead_time` VARCHAR(191) NULL,
    `warranty` VARCHAR(191) NULL,
    `moqs` VARCHAR(191) NULL,
    `touch` VARCHAR(191) NULL,
    `camera` VARCHAR(191) NULL,
    `price_usd` VARCHAR(191) NULL,
    `amount_ewx` VARCHAR(191) NULL,
    `shipping` VARCHAR(191) NULL,
    `landed_cost_usd` VARCHAR(191) NULL,
    `landed_cost_gbp` VARCHAR(191) NULL,
    `quotes` JSON NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `products_slug_key`(`slug`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
